In [1]:
### =========================================
# MATRIX OPERATIONS TOOL
# =========================================

import numpy as np

# =========================================
# FUNCTION: INPUT MATRIX
# =========================================
def input_matrix(name):
    print(f"\nEnter details for {name}:")
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))

    print("Enter elements row-wise:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        if len(row) != cols:
            print("Invalid input. Try again.")
            return input_matrix(name)
        matrix.append(row)

    return np.array(matrix)

# =========================================
# FUNCTION: DISPLAY MATRIX
# =========================================
def display_matrix(mat, title="Result"):
    print(f"\n{title}:")
    print(mat)

# =========================================
# OPERATIONS
# =========================================
def add_matrices():
    A = input_matrix("Matrix A")
    B = input_matrix("Matrix B")
    if A.shape != B.shape:
        print("Addition not possible: Dimensions must match.")
        return
    result = A + B
    display_matrix(result, "Addition Result")

def subtract_matrices():
    A = input_matrix("Matrix A")
    B = input_matrix("Matrix B")
    if A.shape != B.shape:
        print("Subtraction not possible: Dimensions must match.")
        return
    result = A - B
    display_matrix(result, "Subtraction Result")

def multiply_matrices():
    A = input_matrix("Matrix A")
    B = input_matrix("Matrix B")
    if A.shape[1] != B.shape[0]:
        print("Multiplication not possible: Columns of A must equal rows of B.")
        return
    result = np.dot(A, B)
    display_matrix(result, "Multiplication Result")

def transpose_matrix():
    A = input_matrix("Matrix")
    result = A.T
    display_matrix(result, "Transpose Result")

def determinant_matrix():
    A = input_matrix("Matrix")
    if A.shape[0] != A.shape[1]:
        print("Determinant only defined for square matrices.")
        return
    result = np.linalg.det(A)
    print("\nDeterminant:", result)

# =========================================
# MAIN MENU
# =========================================
def main():
    while True:
        print("\n===== MATRIX OPERATIONS TOOL =====")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Transpose")
        print("5. Determinant")
        print("6. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            add_matrices()
        elif choice == '2':
            subtract_matrices()
        elif choice == '3':
            multiply_matrices()
        elif choice == '4':
            transpose_matrix()
        elif choice == '5':
            determinant_matrix()
        elif choice == '6':
            print("Exiting program.")
            break
        else:
            print("Invalid choice. Try again.")

# =========================================
# RUN PROGRAM
# =========================================
if __name__ == "__main__":
    main()


===== MATRIX OPERATIONS TOOL =====
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Enter your choice:  1



Enter details for Matrix A:


Enter number of rows:  3
Enter number of columns:  3


Enter elements row-wise:


Row 1:  1 2 3
Row 2:  4 5 6
Row 3:  7 8 9



Enter details for Matrix B:


Enter number of rows:  3 
Enter number of columns:  3


Enter elements row-wise:


Row 1:  7 8 9 
Row 2:  4 5 6 
Row 3:  1 2 3 



Addition Result:
[[ 8. 10. 12.]
 [ 8. 10. 12.]
 [ 8. 10. 12.]]

===== MATRIX OPERATIONS TOOL =====
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Enter your choice:  6


Exiting program.
